### ISSUE TITLE
What version of the FHIR?

### ISSUE THREAD

**Issue by gregoryhunt** [ocrickard/fhir-rs#2]
What version of the FHIR Standard was this first implementation built from.

**Comment by apps4uco** [comment]
Hi, thanks for the crate. I also have the same question. Im having some issues with the 3.3.0 version so I guess it wasn't built for that... Is there any chance of releasing the software that generates the crate?

**Comment by ocrickard** [comment]
Yep, I generated it with fhir version 4.0.

The code that generates the crate is a bit hacked together if I'm honest, I had meant to clean it up, but never got around to it. I re-generated the library with the 3.3.0 schema here:

[src-3.3.0.zip](https://github.com/ocrickard/fhir-rs/files/7297668/src-3.3.0.zip)

Might need some fixups since the comment structures in 3.3.0 don't seem to follow all the same rules as 4.

Here's the script that generates the library, warning again that I'm not super proud of the script, but it does seem to work!

[bare-lib.zip](https://github.com/ocrickard/fhir-rs/files/7297675/bare-lib.zip)

**Comment by ocrickard** [comment]
Here's a repo for the generation script btw: https://github.com/ocrickard/fhir-rs-parser

**Comment by the-kenny** [comment]
I think it would be a good idea to parametrise the library based on the FHIR version - do separate releases for R4, DSTU3 (if needed) and r5 (which is a prerelease right now). 

HAPI (a popular Java library for FHIR) does this and it works quite well for us.
